const modal=document.querySelector('.game-modal'),stage=document.querySelector('#game-stage'),title=document.querySelector('#game-title'),label=document.querySelector('#game-label'),intro=document.querySelector('#game-intro'),progress=document.querySelector('#game-progress');
let currentGame='';
const games={
 memory:{label:'Case No. 01 · Interactive Investigation',title:'The Tuesday Night Club',intro:'Examine the circumstances of Mrs Jones’s death and uncover the method of poisoning before the others.',render:renderMemory},
 clues:{label:'Case No. 02 · Search for Clues',title:'The Idol House of Astarte',intro:'Find the pearls, letter, crack and bottle hidden in the room.',render:renderClues},
 cipher:{label:'Case No. 03 · Cipher',title:'Ingots of Gold',intro:'Each letter has been replaced by the next one in the alphabet. Decipher the message.',render:renderCipher}
};
function openGame(name){currentGame=name;const g=games[name];label.textContent=g.label;title.textContent=g.title;intro.textContent=g.intro;g.render();modal.showModal()}
document.querySelectorAll('.game-card[data-game]').forEach(card=>{card.addEventListener('click',()=>openGame(card.dataset.game));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openGame(card.dataset.game)}})});
document.querySelector('.close-modal').onclick=()=>modal.close();document.querySelector('#restart-game').onclick=()=>games[currentGame].render();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
function finish(message){stage.innerHTML=`<div class="result"><b>✓</b>${message}</div>`;progress.textContent='Case solved'}
function renderMemory(){const icons=['⌕','⌕','✉','✉','◆','◆','♛','♛'].sort(()=>Math.random()-.5);let first=null,lock=false,matches=0;stage.innerHTML=`<div class="memory-grid">${icons.map((x,i)=>`<button class="memory-card" data-icon="${x}" data-i="${i}" aria-label="Hidden clue">${x}</button>`).join('')}</div>`;progress.textContent='Pairs found: 0 of 4';stage.querySelectorAll('.memory-card').forEach(c=>c.onclick=()=>{if(lock||c===first||c.classList.contains('matched'))return;c.classList.add('open');c.setAttribute('aria-label',`Clue ${c.dataset.icon}`);if(!first){first=c;return}if(first.dataset.icon===c.dataset.icon){first.classList.add('matched');c.classList.add('matched');first=null;matches++;progress.textContent=`Pairs found: ${matches} of 4`;if(matches===4)setTimeout(()=>finish('All clues have been restored!'),450)}else{lock=true;setTimeout(()=>{first.classList.remove('open');c.classList.remove('open');first=null;lock=false},650)}})}
function renderClues(){let found=0;stage.innerHTML='<div class="clue-room"><button class="clue" aria-label="Pearls"></button><button class="clue" aria-label="Letter"></button><button class="clue" aria-label="Crack"></button><button class="clue" aria-label="Bottle"></button></div>';progress.textContent='Clues found: 0 of 4';stage.querySelectorAll('.clue').forEach(c=>c.onclick=()=>{if(c.classList.contains('found'))return;c.classList.add('found');found++;progress.textContent=`Clues found: ${found} of 4`;if(found===4)setTimeout(()=>finish('The room has told its story.'),400)})}
function renderCipher(){stage.innerHTML='<div class="cipher-box"><p class="cipher-key">A→B · B→C · C→D · … · Z→A</p><div class="cipher-code">NFFU VOEFS<br>UIF PME CSJEHF</div><input id="cipher-answer" autocomplete="off" placeholder="Enter the deciphered phrase"><button class="cipher-submit">Check</button></div>';progress.textContent='Hint: move every letter one step back';const check=()=>{const value=document.querySelector('#cipher-answer').value.toLowerCase().replace(/[^a-z]/g,'');if(value==='meetundertheoldbridge')finish('The telegram has been read. You arrived in time!');else{progress.textContent='Not quite. Try moving each letter one step back.'}};stage.querySelector('button').onclick=check;stage.querySelector('input').onkeydown=e=>{if(e.key==='Enter')check()}}
const sound=document.querySelector('.sound-toggle');let audioCtx,osc,gain;if(sound)sound.onclick=()=>{sound.classList.toggle('active');if(sound.classList.contains('active')){audioCtx=new(window.AudioContext||window.webkitAudioContext)();osc=audioCtx.createOscillator();gain=audioCtx.createGain();osc.type='sine';osc.frequency.value=174;gain.gain.value=.018;osc.connect(gain).connect(audioCtx.destination);osc.start();sound.setAttribute('aria-label','Turn off ambient sound')}else{osc?.stop();audioCtx?.close();sound.setAttribute('aria-label','Turn on ambient sound')}};
